name: Publicador Diario de WordPress

on:
  schedule:
    # Se ejecuta todos los días a las 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-publisher:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/creador-contenido
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run WordPress Publisher
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        run: node publish-content.js
