name: Disparador del Ojeador de Duendes

on:
  schedule:
    # Se ejecuta dos veces por semana (Martes y Viernes a las 5:00 AM UTC)
    - cron: '0 5 * * *' # Se ejecuta todos los días a las 5:00 AM
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  trigger-scout:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar al endpoint del orquestador
        run: |
          # Usamos -L para seguir redirecciones y -v para obtener logs detallados
          curl --fail -v -L -X GET "${{ secrets.VERCEL_URL }}/api/orchestrator"