name: Generador de Estrategias de Búsqueda (Ojeador)

on:
  schedule:
    # Se ejecuta todos los días a las 5:00 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  generate-search-strategy:
    runs-on: ubuntu-latest
    outputs:
      jq_success: ${{ steps.format_body.outputs.jq_success }}
    steps:
      - name: 1. Llamar al endpoint del Estratega y guardar las consultas
        id: get_queries
        run: |
          # Usamos -s para modo silencioso, -f para que falle si hay error HTTP, y -o para guardar
          curl -sfL -X GET "${{ secrets.VERCEL_URL }}/api/orchestrator" -o search_queries.json || echo "curl_failed=true" >> $GITHUB_ENV

      - name: 2. Formatear consultas para el cuerpo del Issue
        id: format_body
        outputs:
          jq_success: "false"
        run: |
          # Si el curl falló, no continuamos
          if [ "${{ env.curl_failed }}" == "true" ]; then
            echo "La llamada con curl falló. La API devolvió un código de error HTTP."
            echo "jq_success=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Comprobamos si el fichero tiene contenido
          if [ ! -s search_queries.json ]; then
            echo "El fichero de queries está vacío."
            echo "jq_success=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Intentamos formatear. Si jq falla, el siguiente paso mostrará el contenido.
          if jq -r '.searchQueries | .[] | "- `" + . + "`"' search_queries.json > formatted_body.md; then
            echo "Contenido formateado con éxito."
            {
              echo 'QUERIES_BODY<<EOF';
              echo '### 🤖 Estrategias de Búsqueda Generadas';
              echo '';
              echo 'Esta es la lista de consultas de búsqueda optimizadas generadas por el Estratega. La tarea consiste en ejecutar estas búsquedas en Google y analizar los resultados en busca de nuevos eventos.';
              echo '';
              cat formatted_body.md;
              echo 'EOF';
            } >> "$GITHUB_ENV"
            echo "jq_success=true" >> $GITHUB_OUTPUT
          else
            echo "Error de JQ: El contenido de la respuesta de la API probablemente no es un JSON válido."
            echo "jq_success=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug - Mostrar contenido de la respuesta en caso de error
        if: steps.format_body.outputs.jq_success == 'false'
        run: |
          echo "Contenido del fichero 'search_queries.json' que causó el error:"
          cat search_queries.json
          exit 1 # Forzar el fallo del workflow para que sea visible

      - name: 3. Crear Issue en GitHub con la lista de consultas
        if: steps.format_body.outputs.jq_success == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          ISSUE_TITLE="Estrategias de Búsqueda de Eventos - $(date +'%Y-%m-%d')"
          gh issue create --title "$ISSUE_TITLE" --body "$QUERIES_BODY" --repo $REPO